[package]
name = "fw2tar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.32"
log = "0.4.26"
tempfile = "3.19.0"
thiserror = "2.0.12"
walkdir = "2.5.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "linux_directory_checking"
harness = false
