name: Build and Test Container

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: rehosting-arc
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from ${{ secrets.REHOSTING_ARC_REGISTRY }}"
          openssl s_client -showcerts -connect ${{ secrets.REHOSTING_ARC_REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.REHOSTING_ARC_REGISTRY }}"]
              insecure = true
              http = true

      - name: Log in to Rehosting Arc Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REHOSTING_ARC_REGISTRY }}
          username: ${{ secrets.REHOSTING_ARC_REGISTRY_USER }}
          password: ${{ secrets.REHOSTING_ARC_REGISTRY_PASSWORD }}


      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            REGISTRY=${{ secrets.REHOSTING_ARC_REGISTRY }}/proxy
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ secrets.REHOSTING_ARC_REGISTRY }}/library/fw2tar:${{ github.sha }}
            rehosting/fw2tar:${{ github.sha }}
          cache-from: |
            type=registry,ref=${{ secrets.REHOSTING_ARC_REGISTRY }}/library/fw2tar:cache,mode=max
            type=registry,ref=${{ secrets.REHOSTING_ARC_REGISTRY }}/library/fw2tar:cache-PR-${{github.event.number}},mode=max
          cache-to: |
            type=registry,ref=${{ secrets.REHOSTING_ARC_REGISTRY }}/library/fw2tar:cache,mode=max
            type=registry,ref=${{ secrets.REHOSTING_ARC_REGISTRY }}/library/fw2tar:cache-PR-${{ github.event.number }}

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tests/end_to_end.sh

      - name: Upload AX1800 Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ax1800_listing.txt
          path: tests/results/ax1800_listing.txt.new

      - name: Upload RAX545 Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rax54s_listing.txt
          path: tests/results/rax54s_listing.txt.new

      - name: Upload RAX545 Binwalk Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rax54s_binwalk_log.zip
          path: /tmp/RAX54Sv2-V1.1.4.28.zip_out/RAX54Sv2-V1.1.4.28.binwalk.log
