name: Build and Test Container

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest Docker image for cache
        run: docker pull rehosting/fw2tar:latest || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            rehosting/fw2tar:${{ github.sha }}
            rehosting/fw2tar:latest
          cache-from: type=registry,ref=rehosting/fw2tar:latest
          cache-to: type=inline

      - name: Run Tests
        run: ./tests/end_to_end.sh

      - name: Upload AX1800 Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ax1800_listing.txt
          path: /home/runner/work/fw2tar/fw2tar/tests/results/ax1800_listing.txt.new
